# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MarvelMoviesRank' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarvelMoviesRank
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Alamofire',  '~> 4.8'
  pod 'Kanna',      '~> 4.0.0'

  target 'MarvelMoviesRankTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelMoviesRankUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
